services:
  postgres:
    image: postgres:18
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bpmn_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
volumes:
  pgdata: